// 生成 src/__generated_routes.ts(避免 Vite tree-shake)。
// 与 vite.config.ts 的 generateRoutes 插件逻辑一致,作为独立脚本可在 type-check / CI 阶段调用。

import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import matter from 'gray-matter'

const ROOT = new URL('../', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')
const POSTS_DIR = join(ROOT, 'src/content/posts')
const KNOWLEDGE_DIR = join(ROOT, 'src/content/knowledge')
const GENERATED_FILE = join(ROOT, 'src/__generated_routes.ts')

function fixDates(obj) {
  if (obj === null || obj === undefined) return obj
  if (obj instanceof Date) {
    const y = obj.getUTCFullYear()
    const m = String(obj.getUTCMonth() + 1).padStart(2, '0')
    const d = String(obj.getUTCDate()).padStart(2, '0')
    const hh = String(obj.getUTCHours()).padStart(2, '0')
    const mm = String(obj.getUTCMinutes()).padStart(2, '0')
    const ss = String(obj.getUTCSeconds()).padStart(2, '0')
    return `${y}-${m}-${d} ${hh}:${mm}:${ss}`
  }
  if (Array.isArray(obj)) return obj.map(fixDates)
  if (typeof obj === 'object') {
    const out = {}
    for (const [k, v] of Object.entries(obj)) out[k] = fixDates(v)
    return out
  }
  return obj
}

function pad(n) { return n.toString().padStart(2, '0') }

function buildPostUrl(slug, date) {
  const d = new Date(date)
  if (Number.isNaN(d.getTime())) return `/posts/${slug}/`
  return `/${d.getFullYear()}/${pad(d.getMonth() + 1)}/${pad(d.getDate())}/${slug}/`
}

function isTrue(v) { return v === true || v === 'true' || v === '是' || v === 1 }

function buildPosts() {
  const posts = []
  if (!existsSync(POSTS_DIR)) return { posts, tags: [] }
  for (const file of readdirSync(POSTS_DIR)) {
    if (!file.endsWith('.md')) continue
    const raw = readFileSync(join(POSTS_DIR, file), 'utf-8')
    const { data } = matter(raw)
    const fixed = fixDates(data)
    const slug = file.replace(/\.md$/, '')
    const date = fixed.date ? new Date(fixed.date).toISOString() : new Date().toISOString()
    posts.push({
      title: fixed.title || slug,
      slug,
      date,
      tags: Array.isArray(fixed.tags) ? fixed.tags : [],
      categories: fixed.categories,
      cover: fixed.cover,
      top: isTrue(fixed.top),
      description: fixed.description || '',
      url: buildPostUrl(slug, date),
    })
  }
  posts.sort((a, b) => +new Date(b.date) - +new Date(a.date))
  const tagSet = new Set()
  for (const p of posts) p.tags.forEach((t) => tagSet.add(t))
  return { posts, tags: [...tagSet].sort() }
}

function walkMd(dir) {
  const out = []
  function rec(d) {
    for (const entry of readdirSync(d, { withFileTypes: true })) {
      const full = join(d, entry.name)
      if (entry.isDirectory()) rec(full)
      else if (entry.isFile() && entry.name.endsWith('.md')) out.push(full)
    }
  }
  rec(dir)
  return out
}

function buildKnowledge() {
  if (!existsSync(KNOWLEDGE_DIR)) return []
  const notes = []
  for (const full of walkMd(KNOWLEDGE_DIR)) {
    const rel = full.slice(KNOWLEDGE_DIR.length + 1).replace(/\\/g, '/')
    const parts = rel.split('/')
    if (parts.length < 3) continue
    const domain = parts[parts.length - 3].toLowerCase()
    const topic = parts[parts.length - 2].toLowerCase()
    const slug = parts[parts.length - 1].replace(/\.md$/, '')
    const { data } = matter(readFileSync(full, 'utf-8'))
    notes.push({
      title: data.title || slug,
      slug,
      domain,
      topic,
      url: `/knowledge/${domain}/${topic}/${slug}/`,
    })
  }
  notes.sort((a, b) => a.title.localeCompare(b.title))
  return notes
}

const { posts, tags } = buildPosts()
const knowledge = buildKnowledge()

const code = `// AUTO-GENERATED by scripts/generate-routes.mjs
// 与 vite.config.ts 的 generateRoutes 插件输出保持一致。
// 目的:让所有文章 / 知识笔记 URL 在客户端 bundle 里可用,避免被 Vite tree-shake。

export interface GeneratedPostMeta {
  title: string
  slug: string
  date: string
  tags: string[]
  categories?: string | string[]
  cover?: string
  top?: boolean
  description?: string
  url: string
}

export interface GeneratedKnowledgeMeta {
  title: string
  slug: string
  domain: string
  topic: string
  url: string
}

export const generatedPosts: GeneratedPostMeta[] = ${JSON.stringify(posts, null, 2)}

export const generatedTags: string[] = ${JSON.stringify(tags, null, 2)}

export const generatedKnowledgeNotes: GeneratedKnowledgeMeta[] = ${JSON.stringify(knowledge, null, 2)}
`

mkdirSync(dirname(GENERATED_FILE), { recursive: true })
writeFileSync(GENERATED_FILE, code, 'utf-8')
console.log(`[generate-routes] ${posts.length} posts, ${tags.length} tags, ${knowledge.length} knowledge notes -> ${GENERATED_FILE.replace(ROOT, '')}`)
